vich_uploader:
    db_driver: orm
    mappings:
        fournisseurs:
            uri_prefix: /public/photo_upload
            upload_destination: '%kernel.project_dir%/public/photo_upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: false


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
